name: Deploy Salesforce Metadata
on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
          ./sfdx/install

      - name: Set up Salesforce CLI
        env:
            SFDX_INSTANCE_URL: https://login.salesforce.com
        run: |
              echo ${{ secrets.SALESFORCE_USERNAME }} | sfdx force:auth:web:login -a ci-org -r $SFDX_INSTANCE_URL -d -s -u
              echo ${{ secrets.SALESFORCE_PASSWORD }} | sfdx force:auth:web:login -a ci-org -r $SFDX_INSTANCE_URL -d -s -u
      # Deploy metadata
      - name: Deploy Metadata
        run: |
          # Add the necessary Salesforce CLI deployment commands here
          # For example:
          sfdx force:source:deploy -p force-app/main/default
