name: Deploy Salesforce Metadata
on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          sudo apt-get install curl
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install nodejs
          node -v
          npm install @salesforce/cli --global

      # Authenticate with Salesforce using JWT flow
      - name: Set up Salesforce CLI
        run: |
          echo "${{ secrets.JWT_PRIVATE_KEY }}" | sf login org jwt --username minhthao5648-myxs@force.com -f server.key -i 3MVG9pRzvMkjMb6lZem2d3TGTEHtmLIWhH2vdDXmR2jyUh4JEQuPjy4dZZ9tz5ArVwK14nxPqC8.kYOaRqth8 --instance-url https://minhthao5648-testing-product.my.salesforce.com

      # Deploy metadata
      - name: Deploy Metadata
        run: |
          # Add the necessary Salesforce CLI deployment commands here
          # For example:
          sfdx force:source:deploy -p force-app/main/default