name: Deploy Salesforce Metadata
on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          sudo apt-get install curl
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install nodejs
          node -v
          npm install @salesforce/cli --global

      # Authenticate with Salesforce using JWT flow
      - name: Set up Salesforce CLI
        run: |
          echo "${{ secrets.JWT_PRIVATE_KEY }}" | sf login org jwt -username ${{ secrets.SALESFORCE_USERNAME }} -f $HOME/server.key -i ${{ secrets.CLIENT_ID }} --instance-url ${{ secrets.INSTANCE_URL }}

      # Deploy metadata
      - name: Deploy Metadata
        run: |
          # Add the necessary Salesforce CLI deployment commands here
          # For example:
          sfdx force:source:deploy -p force-app/main/default